name: flutter_03
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  device_preview: ^1.1.0
  meta: ^1.9.1
  http: ^1.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.18.0
  path: ^1.8.3
  
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
